//! For a `build.rs`: prepare module sources so they compile natively.
//!
//! A module source carries two lines only the sandbox build understands:
//! `use talos_sdk_macros::talos_module;` and the `#[talos_module(…)]`
//! attribute. [`generate`] writes a copy of each source without them and a
//! `modules.rs` that declares one module per source, with `talos` in scope.

use std::fmt::Write as _;
use std::io;
use std::path::{Path, PathBuf};

/// One module source to prepare.
#[derive(Debug, Clone)]
pub struct Module {
    /// The Rust module name it is included under (`gmail_get_message`).
    pub name: String,
    pub source: PathBuf,
    /// Tests kept in a file of their own, for a source that carries none
    /// (a module pulled from a running platform is stored without its tests).
    /// Included as `mod tests` inside the module, so the file reaches the
    /// module's private items with its own `use super::*;`.
    pub tests: Option<PathBuf>,
}

impl Module {
    /// A module named after `dir_name`, with `-` turned into `_`.
    #[must_use]
    pub fn new(dir_name: &str, source: PathBuf) -> Self {
        Self {
            name: dir_name.replace('-', "_"),
            source,
            tests: None,
        }
    }

    /// The same module with its tests read from `tests`.
    #[must_use]
    pub fn with_tests(mut self, tests: PathBuf) -> Self {
        self.tests = Some(tests);
        self
    }
}

/// The source without the SDK-macro import and attribute. Every other line is
/// kept as written, so line numbers in a compiler message differ from the
/// original by at most two.
#[must_use]
pub fn strip_sdk_macro(source: &str) -> String {
    let mut out = String::with_capacity(source.len());
    for line in source.lines() {
        let t = line.trim();
        // The attribute is written both ways: bare after the import, and
        // path-qualified with no import at all.
        if t == "use talos_sdk_macros::talos_module;"
            || t.starts_with("#[talos_module")
            || t.starts_with("#[talos_sdk_macros::talos_module")
        {
            continue;
        }
        out.push_str(line);
        out.push('\n');
    }
    out
}

/// A name usable as a Rust module name: ASCII letters, digits and `_`, not
/// starting with a digit.
fn valid_name(name: &str) -> bool {
    let mut chars = name.chars();
    chars
        .next()
        .is_some_and(|c| c.is_ascii_alphabetic() || c == '_')
        && chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
}

/// Write `<out_dir>/<name>.rs` for each module and `<out_dir>/modules.rs`
/// declaring them. Prints `cargo:rerun-if-changed` for every source.
///
/// The including crate must have `talos` at its root
/// (`pub use talos_module_testkit::talos;`).
pub fn generate(modules: &[Module], out_dir: &Path) -> io::Result<()> {
    let mut index = String::from("// Generated by talos_module_testkit::build::generate.\n");
    for m in modules {
        if !valid_name(&m.name) {
            return Err(io::Error::new(
                io::ErrorKind::InvalidInput,
                format!("'{}' is not usable as a Rust module name", m.name),
            ));
        }
        let source = std::fs::read_to_string(&m.source)?;
        let prepared = out_dir.join(format!("{}.rs", m.name));
        std::fs::write(&prepared, strip_sdk_macro(&source))?;
        println!("cargo:rerun-if-changed={}", m.source.display());
        // `{:?}` on a path writes it as a Rust string literal.
        let tests = match &m.tests {
            None => String::new(),
            Some(path) => {
                println!("cargo:rerun-if-changed={}", path.display());
                // Included from where it is, not copied: a compiler message
                // about a test names the file the author edits.
                let absolute = std::fs::canonicalize(path)?;
                format!(
                    "    #[cfg(test)]\n    mod tests {{\n        include!({:?});\n    }}\n",
                    absolute.display().to_string()
                )
            }
        };
        let _ = writeln!(
            index,
            "#[allow(dead_code, unused_imports)]\npub mod {} {{\n    use crate::talos;\n    include!({:?});\n{tests}}}",
            m.name,
            prepared.display().to_string()
        );
    }
    std::fs::write(out_dir.join("modules.rs"), index)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn only_the_two_sdk_lines_are_removed() {
        let src = "use talos_sdk_macros::talos_module;\nuse serde::Deserialize;\n\n    #[talos_module(world = \"http-node\")]\npub fn run() {}\n// talos_module in a comment stays\n";
        assert_eq!(
            strip_sdk_macro(src),
            "use serde::Deserialize;\n\npub fn run() {}\n// talos_module in a comment stays\n"
        );
        // The path-qualified attribute, written without the import.
        assert_eq!(
            strip_sdk_macro(
                "#[talos_sdk_macros::talos_module(world = \"http-node\")]\nfn run() {}\n"
            ),
            "fn run() {}\n"
        );
    }

    #[test]
    fn a_separate_tests_file_is_included_inside_the_module() {
        let dir = std::env::temp_dir().join(format!("testkit-gen-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let source = dir.join("module.rs");
        let tests = dir.join("tests.rs");
        std::fs::write(&source, "fn private() -> u8 { 1 }\n").unwrap();
        std::fs::write(
            &tests,
            "use super::*;\n#[test]\nfn t() { assert_eq!(private(), 1); }\n",
        )
        .unwrap();
        let out = dir.join("out");
        std::fs::create_dir_all(&out).unwrap();

        generate(
            &[
                Module::new("with-tests", source.clone()).with_tests(tests.clone()),
                Module::new("without", source),
            ],
            &out,
        )
        .unwrap();
        let index = std::fs::read_to_string(out.join("modules.rs")).unwrap();
        let (first, second) = index.split_once("pub mod without").unwrap();
        assert!(first.contains("pub mod with_tests {"), "{index}");
        assert!(
            first.contains("#[cfg(test)]\n    mod tests {")
                && first.contains(&format!(
                    "{:?}",
                    std::fs::canonicalize(&tests).unwrap().display().to_string()
                )),
            "the tests file is included inside the module: {index}"
        );
        assert!(!second.contains("mod tests"), "{index}");
        // A tests file that is not there is an error, not a module without tests.
        assert!(generate(
            &[Module::new("gone", dir.join("module.rs")).with_tests(dir.join("absent.rs"))],
            &out
        )
        .is_err());
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn a_directory_name_becomes_a_module_name_or_is_refused() {
        assert_eq!(
            Module::new("gmail-get-message", PathBuf::new()).name,
            "gmail_get_message"
        );
        assert!(valid_name("a_1"));
        for bad in ["", "1a", "a-b", "a b", "a;b", "é"] {
            assert!(!valid_name(bad), "{bad}");
        }
        let dir = std::env::temp_dir();
        let bad = Module {
            name: "x; mod y".into(),
            source: PathBuf::from("/nonexistent"),
            tests: None,
        };
        assert!(
            generate(&[bad], &dir).is_err(),
            "a name is never written into the index unchecked"
        );
    }
}
