[package]
name = "talos-errors"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
axum = { workspace = true, features = ["json"] }
bcrypt.workspace = true
jsonwebtoken = { workspace = true, features = ["rust_crypto", "use_pem"] }
serde_json.workspace = true
sqlx = { workspace = true, features = ["postgres", "runtime-tokio", "tls-rustls-ring-webpki"] }
tracing.workspace = true

[lints]
workspace = true
