#!/usr/bin/env bash
# Generate the migration baseline (RFC 0009): a schema snapshot + a
# _sqlx_migrations seed so a fresh environment can skip re-running the
# whole migration chain up to a cutpoint version V.
#
# Does NOT edit or delete any migration — the chain stays the source of
# truth and stays embedded in the binary. This produces the ADDITIVE
# fast-path artifacts under migrations/.baseline/.
#
# Requires a live, EMPTY, disposable Postgres (pgvector image — the schema
# uses vector(N) columns). Never point this at a real database.
#
# Usage:
#   BASELINE_DATABASE_URL=postgres://user:pw@localhost:5433/baseline_gen \
#     bash scripts/generate-schema-baseline.sh [CUTPOINT_VERSION]
#
# CUTPOINT_VERSION (optional): the highest migration version to fold into
# the baseline. Default: the highest version present in migrations/. Every
# migration with version <= cutpoint is seeded into _sqlx_migrations;
# migrations above it remain in the runtime tail.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
BASELINE_DIR="migrations/.baseline"

red()   { printf '\033[1;31m%s\033[0m\n' "$*" >&2; }
green() { printf '\033[1;32m%s\033[0m\n' "$*"; }
bold()  { printf '\033[1m%s\033[0m\n' "$*"; }

: "${BASELINE_DATABASE_URL:?set BASELINE_DATABASE_URL to a DISPOSABLE empty Postgres}"
# PG_DUMP_BIN override: pg_dump refuses servers NEWER than itself, so a
# host with an older client (e.g. Homebrew pg 14 vs the pg17 server) can
# point this at a matching binary or a docker-run wrapper.
PG_DUMP="${PG_DUMP_BIN:-pg_dump}"
command -v sqlx >/dev/null || { red "sqlx-cli not found — cargo install sqlx-cli"; exit 1; }
"$PG_DUMP" --version >/dev/null 2>&1 || { red "pg_dump not usable (PG_DUMP_BIN=$PG_DUMP)"; exit 1; }

# sqlx computes migration checksums as SHA-384 of the raw file bytes.
# Match that exactly (openssl is portable; shasum -a 384 is the fallback).
sha384_hex() {
    if command -v openssl >/dev/null; then
        openssl dgst -sha384 -hex "$1" | awk '{print $NF}'
    else
        shasum -a 384 "$1" | awk '{print $1}'
    fi
}

# Migration filenames are <version>_<description>.sql. sqlx parses the
# version as the leading integer run and the description as the rest.
migration_version() { basename "$1" | sed -E 's/^([0-9]+)_.*/\1/'; }
migration_desc()    { basename "$1" | sed -E 's/^[0-9]+_(.*)\.sql$/\1/; s/_/ /g'; }

FILES=(migrations/*.sql)
[ "${#FILES[@]}" -gt 0 ] || { red "no migrations found"; exit 1; }

# Default cutpoint = highest version present.
CUTPOINT="${1:-$(for f in "${FILES[@]}"; do migration_version "$f"; done | sort -n | tail -1)}"
bold "▶ generating baseline at cutpoint version $CUTPOINT"

# 1. Apply the FULL chain against the disposable DB (sqlx records
#    _sqlx_migrations with the canonical checksums as it goes).
bold "▶ applying full migration chain to the disposable DB"
DATABASE_URL="$BASELINE_DATABASE_URL" sqlx migrate run --source migrations

mkdir -p "$BASELINE_DIR"

# 2. Dump the schema (structure only — no data, no owner/priv noise so the
#    snapshot is portable and diff-stable for the verifier).
bold "▶ dumping schema snapshot → $BASELINE_DIR/schema.sql"
# The grep strips the \restrict/\unrestrict psql meta-commands newer
# pg_dump point releases emit (a psql-injection hardening irrelevant to
# a self-generated schema artifact): older psql clients reject them, and
# stripping keeps the artifact stable across pg_dump point versions —
# which matters because the verifier diffs dumps.
"$PG_DUMP" --schema-only --no-owner --no-privileges --no-comments \
    "$BASELINE_DATABASE_URL" \
    | grep -vE '^\\(un)?restrict ' > "$BASELINE_DIR/schema.sql"

# 3. Emit the _sqlx_migrations seed for every migration <= cutpoint, using
#    the same SHA-384 sqlx computes. `\x` bytea hex-literal form; success=true;
#    execution_time=0 (informational column, not part of the skip decision).
bold "▶ emitting _sqlx_migrations seed → $BASELINE_DIR/seed_sqlx_migrations.sql"
{
    echo "-- Generated by scripts/generate-schema-baseline.sh (RFC 0009). DO NOT EDIT BY HAND."
    echo "-- Seeds _sqlx_migrations for every migration <= cutpoint $CUTPOINT so"
    echo "-- sqlx::migrate! skips them after migrations/.baseline/schema.sql is loaded."
    echo "INSERT INTO _sqlx_migrations (version, description, installed_on, success, checksum, execution_time) VALUES"
    first=1
    for f in $(printf '%s\n' "${FILES[@]}" | sort); do
        v="$(migration_version "$f")"
        [ "$v" -le "$CUTPOINT" ] || continue
        desc="$(migration_desc "$f" | sed "s/'/''/g")"
        sum="$(sha384_hex "$f")"
        sep=","; [ "$first" -eq 1 ] && sep="" && first=0
        printf "%s\n  (%s, '%s', now(), true, '\\\\x%s'::bytea, 0)" "$sep" "$v" "$desc" "$sum"
    done
    echo ""
    echo "ON CONFLICT (version) DO NOTHING;"
} > "$BASELINE_DIR/seed_sqlx_migrations.sql"

# 4. Record the cutpoint + provenance (no wall-clock in the file body so the
#    artifact is reproducible; the git commit records when).
{
    echo "cutpoint_version=$CUTPOINT"
    echo "migrations_folded=$(for f in "${FILES[@]}"; do v=$(migration_version "$f"); [ "$v" -le "$CUTPOINT" ] && echo x; done | wc -l | tr -d ' ')"
    echo "migrations_total=${#FILES[@]}"
} > "$BASELINE_DIR/CUTPOINT"

green "✓ baseline generated at cutpoint $CUTPOINT"
echo "  → $BASELINE_DIR/schema.sql, seed_sqlx_migrations.sql, CUTPOINT"
echo "  Next: run 'make verify-schema-baseline' (proves baseline+seed+tail == full chain)."
echo "  The baseline is NOT consumed by any install path until phase 2 (RFC 0009)."
