#!/usr/bin/env bash
#
# scaffold-integration.sh — create the 10-file skeleton for a new
# push-notification integration.
#
# What this does: creates empty source + frontend + docs files at
# the right paths with one-line module docstrings pointing at
# `docs/integration-pattern.md` and the nearest reference
# implementation.
#
# What this DOESN'T do: fill in the logic. That's the whole point
# of reading the pattern doc — the logic varies per upstream and
# can't be templated without producing wrong-for-your-case code.
# Think of this script as `mkdir + touch + pointer comments`, not
# `cargo-generate`.
#
# Usage:
#   scripts/scaffold-integration.sh <snake_name> <CamelName>
#
# Example:
#   scripts/scaffold-integration.sh slack_events SlackEvents
#
# The script refuses to run if ANY of the target files already
# exist, so you can't accidentally overwrite work. To re-scaffold,
# delete the directory first.

set -euo pipefail

if [[ $# -lt 2 ]]; then
    cat <<EOF >&2
Usage: $0 <snake_name> <CamelName>

  snake_name  lowercase_with_underscores, used for module paths
              and integration_state.integration_name
  CamelName   CamelCase, used for Rust struct + type names

Examples:
  $0 slack_events SlackEvents
  $0 github_webhooks GithubWebhooks
  $0 jira_webhooks JiraWebhooks
EOF
    exit 2
fi

SNAKE="$1"
CAMEL="$2"
UPPER=$(echo "$SNAKE" | tr '[:lower:]' '[:upper:]')
REPO_ROOT=$(cd "$(dirname "$0")/.." && pwd)

CONTROLLER_DIR="$REPO_ROOT/controller/src/$SNAKE"
FRONTEND_FILE="$REPO_ROOT/frontend/src/components/settings/${CAMEL}WatchChannels.tsx"
DOCS_FILE="$REPO_ROOT/docs/$SNAKE-push-setup.md"

# ----------------------------------------------------------------
# Pre-flight: refuse to clobber existing work.
# ----------------------------------------------------------------
CLOBBERS=()
[[ -d "$CONTROLLER_DIR" ]] && CLOBBERS+=("$CONTROLLER_DIR (directory)")
[[ -f "$FRONTEND_FILE" ]] && CLOBBERS+=("$FRONTEND_FILE")
[[ -f "$DOCS_FILE" ]] && CLOBBERS+=("$DOCS_FILE")
if [[ ${#CLOBBERS[@]} -gt 0 ]]; then
    echo "❌ Refusing to overwrite existing files:" >&2
    printf '   %s\n' "${CLOBBERS[@]}" >&2
    echo "" >&2
    echo "   Delete them first if you really want to re-scaffold." >&2
    exit 1
fi

mkdir -p "$CONTROLLER_DIR"

# Shared header emitted into every generated source file.
pattern_header() {
    local file_role="$1"
    local ref_file="$2"
    cat <<EOF
//! $file_role for the $SNAKE integration.
//!
//! SCAFFOLD — this file was generated by
//! \`scripts/scaffold-integration.sh\`. Its implementation is
//! intentionally missing; fill it in following
//! \`docs/integration-pattern.md\`. The two reference
//! implementations to crib from are \`controller/src/gmail/$ref_file\`
//! and \`controller/src/google_calendar/$ref_file\` (if that file
//! exists there).
//!
//! Before editing: read the "Quick start" + "Claude Code workflow"
//! sections of the pattern doc. They give the five up-front
//! questions that determine what goes here.

// TODO(${SNAKE}): remove this once the module has real content.
#![allow(unused)]
EOF
}

write_stub() {
    local path="$1"
    local role="$2"
    local ref="$3"
    pattern_header "$role" "$ref" > "$path"
    echo "  $path"
}

echo "▶ Scaffolding $SNAKE integration..."
echo ""
echo "Controller module:"

write_stub "$CONTROLLER_DIR/mod.rs" \
    "Module root" "mod.rs"
cat >> "$CONTROLLER_DIR/mod.rs" <<EOF

// Wire the submodules here as they're filled in:
// pub mod admin;
// pub mod api;
// pub mod dispatch;
// pub mod handlers;
// pub mod scheduler;
// pub mod watch;
// pub mod watch_channel_service;
// pub mod webhook_token;  // for HMAC-auth integrations (gcal-style)
// pub mod pubsub_jwt;     // for upstream-JWT-auth integrations (gmail-style)
EOF

write_stub "$CONTROLLER_DIR/api.rs" \
    "Upstream API client — the endpoints the watch path needs" "api.rs"
write_stub "$CONTROLLER_DIR/watch.rs" \
    "Watch-channel lifecycle on integration_state" "watch.rs"
write_stub "$CONTROLLER_DIR/scheduler.rs" \
    "Hourly renewal task" "scheduler.rs"
write_stub "$CONTROLLER_DIR/handlers.rs" \
    "REST + webhook handlers" "handlers.rs"
write_stub "$CONTROLLER_DIR/admin.rs" \
    "Admin-only endpoints (two-gate: ENABLE_ADMIN_OPS + X-Admin-Secret)" \
    "admin.rs"
write_stub "$CONTROLLER_DIR/dispatch.rs" \
    "WASM dispatch — one JobRequest per upstream event" "dispatch.rs"
write_stub "$CONTROLLER_DIR/watch_channel_service.rs" \
    "List-view projection + recent_failure enrichment" \
    "watch_channel_service.rs"

# One of these two exists per integration depending on auth shape.
# Generate both as stubs; the developer deletes the one they don't
# use.
write_stub "$CONTROLLER_DIR/webhook_token.rs" \
    "HMAC-signed webhook token (DELETE if using upstream-JWT auth instead)" \
    "../google_calendar/webhook_token.rs"
write_stub "$CONTROLLER_DIR/pubsub_jwt.rs" \
    "Upstream-signed JWT verification (DELETE if using HMAC-token auth instead)" \
    "pubsub_jwt.rs"

echo ""
echo "Frontend component:"
cat > "$FRONTEND_FILE" <<EOF
/**
 * ${CAMEL}WatchChannels — settings-page panel for the $SNAKE
 * integration.
 *
 * SCAFFOLD — generated by scripts/scaffold-integration.sh. Mirror
 * GmailWatchChannels.tsx or GoogleCalendarWatchChannels.tsx; both
 * are complete reference implementations of the React Query +
 * optimistic-update pattern described in
 * docs/integration-pattern.md (section 9).
 *
 * Before editing: confirm the five quick-start questions in the
 * pattern doc are answered, especially "how many watches per user"
 * (affects table shape) and "which fields make sense to show".
 */

import React from "react";

export function ${CAMEL}WatchChannels(): React.ReactElement | null {
    // TODO(${SNAKE}): mirror GmailWatchChannels.tsx structure.
    // Render nothing until implementation is fleshed out, so
    // importing this into IntegrationsManager doesn't break layout.
    return null;
}
EOF
echo "  $FRONTEND_FILE"

echo ""
echo "Operator runbook:"
cat > "$DOCS_FILE" <<EOF
# $CAMEL push-notification setup

SCAFFOLD — generated by \`scripts/scaffold-integration.sh\`. Mirror
\`docs/gmail-push-setup.md\` or \`docs/gcal-live-test.md\` (both are
complete operator runbooks for push integrations).

## Prerequisites

- TODO: enumerate upstream-specific account / scope / infra
  requirements.

## Architecture

- TODO: one-paragraph diagram of how pushes flow from upstream ->
  our webhook -> dispatch.

## Step-by-step setup

- TODO: \`gcloud\` / \`gh\` / \`curl\` commands the operator runs
  once, with concrete variable substitution examples.

## Environment variables Talos expects

\`\`\`bash
${UPPER}_WEBHOOK_SECRET=         # TODO: describe
${UPPER}_DEFAULT_FILTER_IDS=     # TODO: describe
\`\`\`

## Verification

- TODO: step-by-step "send a test event, watch for log line,
  confirm audit row" sequence.

## Teardown

- TODO: commands to reverse the setup.

## Cost expectations

- TODO: at personal scale, upstream free-tier coverage.
EOF
echo "  $DOCS_FILE"

echo ""
echo "✅ Scaffold complete for '$SNAKE' ($CAMEL)."
echo ""
cat <<EOF
Next steps:

  1. READ \`docs/integration-pattern.md\` end-to-end if you haven't.
     Start with the "Quick start" five questions — answering all
     five BEFORE coding prevents mid-implementation re-architecture.

  2. DECIDE: HMAC-signed webhook token (gcal-style) OR
     upstream-signed JWT verification (gmail-style)?
     Delete whichever you're NOT using:
       rm controller/src/$SNAKE/webhook_token.rs   # if using JWT
       rm controller/src/$SNAKE/pubsub_jwt.rs      # if using HMAC

  3. OPEN the reference implementation most similar to your upstream:
       controller/src/gmail/     (Pub/Sub + JWT + OAuth-with-history)
       controller/src/google_calendar/  (webhook + HMAC + sync-token)

  4. IMPLEMENT the ten pieces in the order listed in the pattern
     doc's "Required pieces" checklist. Compile + test green
     between each piece.

  5. WIRE UP in main.rs:
       mod $SNAKE;
       ...route + service construction...

  6. WIRE UP the frontend component in
     frontend/src/components/settings/IntegrationsManager.tsx
     (add import + render below the other integration panels).

  7. COMPLETE docs/$SNAKE-push-setup.md so the next operator can
     reproduce the setup cold.

Suggested Claude Code workflow (if that's what you're using):
  * Spawn Explore subagent × 2 in parallel against gmail/ and
    google_calendar/ for a fast survey.
  * Spawn Plan subagent to sequence the ten files.
  * Implement + test green.
  * Spawn code-review subagent on the webhook_token/pubsub_jwt
    and renewal paths specifically.
EOF
