[package]
name = "talos-csrf"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
axum = { workspace = true, features = ["json"] }
dashmap.workspace = true
hex.workspace = true
talos-random = { path = "../talos-random" }
serde_json.workspace = true
subtle.workspace = true
talos-config = { path = "../talos-config" }
talos-auth-types = { path = "../talos-auth-types" }
tower-cookies.workspace = true
tracing.workspace = true

[lints]
workspace = true
