[package]
name = "talos-plaid-connect"
description = "Connecting and disconnecting bank accounts through Plaid Link"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
axum = { version = "0.8", features = ["json"] }
serde.workspace = true
serde_json.workspace = true
sqlx = { version = "0.8", default-features = false, features = ["postgres", "runtime-tokio-rustls", "macros", "uuid", "chrono"] }
talos-organizations = { path = "../talos-organizations" }
talos-plaid = { path = "../talos-plaid" }
talos-secrets-manager = { path = "../talos-secrets-manager" }
tracing.workspace = true
uuid.workspace = true

[lints]
workspace = true
