{{- if .Values.vault.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "talos.componentName" (list . "vault") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "talos.componentLabels" (list . "vault") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8200
      targetPort: http
      protocol: TCP
  selector:
    {{- include "talos.componentSelectorLabels" (list . "vault") | nindent 4 }}
{{- end }}
