{{- if and .Values.vault.enabled .Values.vault.init.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "talos.componentName" (list . "vault-init") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "talos.componentLabels" (list . "vault") | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
