{{- if and .Values.controller.enabled .Values.controller.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "talos.componentName" (list . "controller") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "talos.componentLabels" (list . "controller") | nindent 4 }}
  {{- with .Values.controller.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.controller.ingress.className }}
  {{- with .Values.controller.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.controller.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "talos.componentName" (list $ "controller") }}
                port:
                  number: {{ $.Values.controller.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
