{{- if .Values.postgres.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "talos.componentName" (list . "postgres") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "talos.componentLabels" (list . "postgres") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
  selector:
    {{- include "talos.componentSelectorLabels" (list . "postgres") | nindent 4 }}
{{- end }}
