//! Microsoft 365 connection: the OAuth consent that lets a module call the
//! Microsoft 365 API on the owner's behalf.
//!
//! OAuth only. The reading is done by a sandboxed module with a
//! `vault://oauth/microsoft_365/...` reference; this crate exists so that token
//! can be obtained, refreshed and revoked.
//!
//! * Tokens live in the unified credential store, at
//!   `oauth/microsoft_365/{user_id}/{provider_key}/…`; the table here holds
//!   metadata only.
//! * The flow is `talos_oauth`'s: state bound to the user and to the browser
//!   that started it, single-use, PKCE. Nothing here re-implements it.
//!
//! * Read-only: the mailbox and the calendar, and the account's own profile
//!   to know which account it is. Sending mail is not asked for.
//! * Microsoft rotates the refresh token on every refresh; the credential
//!   store persists whichever one the last refresh returned.
//!
//! Generated by `scripts/new-integration.py`. Setup and behaviour:
//! `docs/microsoft-365-setup.md`.

pub mod handlers;

use anyhow::{anyhow, Context, Result};
use chrono::{DateTime, Utc};
use sqlx::{Pool, Postgres};
use std::sync::{Arc, LazyLock};
use uuid::Uuid;

use talos_oauth::OAuthCredentialService;

/// Provider string: the state-token match key and the vault-path segment.
pub const PROVIDER: &str = "microsoft_365";

/// The delegated Graph permissions the consent asks for. `offline_access` is
/// what makes Microsoft issue a refresh token; `User.Read` answers which
/// account this is; the other two are what the modules read.
pub const SCOPES: &[&str] = &["offline_access", "User.Read", "Mail.Read", "Calendars.Read"];

/// The scopes a connection is useless without: at least one must be granted.
const READING_SCOPES: &[&str] = &["Mail.Read", "Calendars.Read"];

/// The endpoints under `MICROSOFT_365_TENANT` (`talos_oauth` resolves it, so
/// the connect here and the refresh there hit the same one). Built once:
/// `AuthorizeRequest` wants a `&'static str` and the tenant is part of the
/// path. `None` when the variable names no tenant; no connect can start then.
static AUTH_URL: LazyLock<Option<String>> =
    LazyLock::new(|| endpoint(talos_oauth::microsoft_365_authorize_url()));
static TOKEN_URL: LazyLock<Option<String>> =
    LazyLock::new(|| endpoint(talos_oauth::microsoft_365_token_url()));

fn endpoint(url: Result<String>) -> Option<String> {
    url.map_err(|e| tracing::error!("Microsoft 365 connect is unavailable: {e}"))
        .ok()
}

fn no_tenant() -> anyhow::Error {
    anyhow!("MICROSOFT_365_TENANT names no tenant")
}
/// Answers "which account is this?" for the token just issued.
const ACCOUNT_URL: &str = "https://graph.microsoft.com/v1.0/me?$select=id,userPrincipalName,mail";

/// Where the provider sends the browser back when no redirect is configured
/// (the development stack).
const DEFAULT_REDIRECT_URI: &str = "http://localhost:8000/api/microsoft-365/callback";

/// One hardened client for the token exchange and the account lookup
/// (redirects off, connect and total timeouts — lint 49).
static HTTP: LazyLock<reqwest::Client> = LazyLock::new(|| {
    talos_http_utils::trusted_client::build_integration_client(std::time::Duration::from_secs(15))
});

/// A connected Microsoft 365 account. Metadata only — no token is ever here.
#[derive(Debug, Clone, sqlx::FromRow)]
pub struct Microsoft365Integration {
    pub id: Uuid,
    pub user_id: Uuid,
    /// The provider's stable id for the account; the vault-path segment.
    pub provider_key: String,
    /// What the settings card shows for this connection.
    pub account_label: Option<String>,
    pub token_expires_at: Option<DateTime<Utc>>,
    pub scope: Option<String>,
    pub is_active: bool,
    pub created_at: Option<DateTime<Utc>>,
    pub updated_at: Option<DateTime<Utc>>,
}

/// The connect flow for Microsoft 365.
pub struct Microsoft365Service {
    db_pool: Pool<Postgres>,
    client_id: Option<String>,
    client_secret: Option<String>,
    redirect_uri: String,
    credentials_service: Option<Arc<OAuthCredentialService>>,
    /// `None` when `MICROSOFT_365_TENANT` names no tenant.
    token_url: Option<String>,
    account_url: String,
}

/// Hand-written so a stray `{:?}` never prints the client secret (lint 37).
impl std::fmt::Debug for Microsoft365Service {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Microsoft365Service")
            .field("client_id", &self.client_id)
            .field("client_secret", &"[REDACTED]")
            .field("redirect_uri", &self.redirect_uri)
            .field(
                "has_credentials_service",
                &self.credentials_service.is_some(),
            )
            .finish()
    }
}

/// An environment variable, with empty meaning unset (a helm placeholder
/// must not become a client id).
fn env_value(name: &str) -> Option<String> {
    std::env::var(name)
        .ok()
        .map(|v| v.trim().to_string())
        .filter(|v| !v.is_empty())
}

impl Microsoft365Service {
    pub fn new(db_pool: Pool<Postgres>) -> Self {
        Self {
            db_pool,
            client_id: env_value("MICROSOFT_365_CLIENT_ID"),
            client_secret: env_value("MICROSOFT_365_CLIENT_SECRET"),
            redirect_uri: env_value("MICROSOFT_365_REDIRECT_URI")
                .unwrap_or_else(|| DEFAULT_REDIRECT_URI.to_string()),
            credentials_service: None,
            token_url: TOKEN_URL.clone(),
            account_url: ACCOUNT_URL.to_string(),
        }
    }

    /// Attach the unified credential service. Without it a callback is
    /// refused: there is nowhere safe to put the tokens.
    #[must_use]
    pub fn with_credentials_service(mut self, svc: Arc<OAuthCredentialService>) -> Self {
        self.credentials_service = Some(svc);
        self
    }

    /// A service with the given client and endpoints. For tests, which stand
    /// a loopback server in for the provider; deliberately not reachable from
    /// configuration, so a deployment cannot be pointed at another token
    /// endpoint.
    #[doc(hidden)]
    pub fn for_tests(
        db_pool: Pool<Postgres>,
        client: Option<(&str, &str)>,
        token_url: &str,
        account_url: &str,
    ) -> Self {
        Self {
            db_pool,
            client_id: client.map(|(id, _)| id.to_string()),
            client_secret: client.map(|(_, secret)| secret.to_string()),
            redirect_uri: DEFAULT_REDIRECT_URI.to_string(),
            credentials_service: None,
            token_url: Some(token_url.to_string()),
            account_url: account_url.to_string(),
        }
    }

    /// Whether the OAuth client is configured and `MICROSOFT_365_TENANT`, if
    /// set, names a tenant.
    pub fn is_configured(&self) -> bool {
        self.client_id.is_some()
            && self.client_secret.is_some()
            && AUTH_URL.is_some()
            && self.token_url.is_some()
    }

    /// The authorize URL for `user_id`, with the state bound to that user and
    /// to the browser `binding` belongs to. Returns `(url, state)`.
    pub async fn get_authorization_url(
        &self,
        user_id: Uuid,
        binding: &talos_oauth::BrowserBinding,
    ) -> Result<(String, String)> {
        talos_oauth::authorization_url(&self.db_pool, self, user_id, binding).await
    }

    /// Complete the connect. The user comes from the state token, never from
    /// a session; the state is consumed before the code is exchanged.
    pub async fn handle_callback(
        &self,
        code: String,
        state: String,
        presented_binding: Option<&str>,
    ) -> Result<Microsoft365Integration> {
        talos_oauth::handle_oauth_callback(&self.db_pool, self, &code, &state, presented_binding)
            .await
    }

    /// Insert the account's row, or bring a disconnected one back.
    ///
    /// `updated_at` is left to the table's trigger.
    async fn upsert_integration(
        &self,
        user_id: Uuid,
        provider_key: &str,
        account_label: Option<&str>,
        token_expires_at: DateTime<Utc>,
        scope: &str,
    ) -> Result<Microsoft365Integration> {
        sqlx::query_as::<_, Microsoft365Integration>(
            r"
            INSERT INTO microsoft_365_integrations (
                user_id, provider_key, account_label, token_expires_at, scope
            )
            VALUES ($1, $2, $3, $4, $5)
            ON CONFLICT (user_id, provider_key)
            DO UPDATE SET
                account_label = EXCLUDED.account_label,
                token_expires_at = EXCLUDED.token_expires_at,
                scope = EXCLUDED.scope,
                is_active = TRUE
            RETURNING id, user_id, provider_key, account_label, token_expires_at, scope,
                      is_active, created_at, updated_at
            ",
        )
        .bind(user_id)
        .bind(provider_key)
        .bind(account_label)
        .bind(token_expires_at)
        .bind(scope)
        .fetch_one(&self.db_pool)
        .await
        .context("Failed to upsert Microsoft 365 integration")
    }
}

/// A provider account id as a vault-path segment: the id itself when it is
/// short and made of characters a path segment may hold, otherwise refused.
/// A `/` would re-root the credential's path.
fn provider_key_for(account_id: &str) -> Result<String> {
    let id = account_id.trim();
    let ok = !id.is_empty()
        && id.len() <= 128
        && id
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || matches!(c, '-' | '_' | '.' | '@'));
    if ok {
        Ok(id.to_string())
    } else {
        Err(anyhow!(
            "Microsoft 365 returned an account id that cannot key a credential"
        ))
    }
}

#[async_trait::async_trait]
impl talos_oauth::OAuthIntegration for Microsoft365Service {
    type Connected = Microsoft365Integration;

    fn provider(&self) -> &'static str {
        PROVIDER
    }

    fn authorize_request(&self) -> Result<talos_oauth::AuthorizeRequest<'static>> {
        Ok(talos_oauth::AuthorizeRequest {
            provider: PROVIDER,
            auth_url: AUTH_URL.as_deref().ok_or_else(no_tenant)?,
            token_url: TOKEN_URL.as_deref().ok_or_else(no_tenant)?,
            client_id: self
                .client_id
                .clone()
                .ok_or_else(|| anyhow!("MICROSOFT_365_CLIENT_ID is not set"))?,
            client_secret: self
                .client_secret
                .clone()
                .ok_or_else(|| anyhow!("MICROSOFT_365_CLIENT_SECRET is not set"))?,
            redirect_uri: self.redirect_uri.clone(),
            scopes: SCOPES,
            // The refresh token comes from `offline_access` in the scopes.
            // `select_account` shows the account picker even when the browser
            // is signed in to one, so a second account can be connected.
            extra_params: &[("prompt", "select_account")],
        })
    }

    async fn complete_callback(
        &self,
        _pool: &sqlx::PgPool,
        code: &str,
        consumed: talos_oauth::ConsumedOAuthState,
    ) -> Result<Microsoft365Integration> {
        // The user is the one the state was minted for. The state has already
        // been consumed and its browser binding checked by the shared driver.
        let user_id = consumed.user_id;
        let cred_svc = self.credentials_service.as_ref().ok_or_else(|| {
            anyhow!("Credential service not configured — cannot store Microsoft 365 tokens")
        })?;
        let client_id = self
            .client_id
            .clone()
            .ok_or_else(|| anyhow!("MICROSOFT_365_CLIENT_ID is not set"))?;
        let client_secret = self
            .client_secret
            .clone()
            .ok_or_else(|| anyhow!("MICROSOFT_365_CLIENT_SECRET is not set"))?;

        // ---- 1. Exchange the code ----------------------------------------
        let mut form = vec![
            ("grant_type", "authorization_code".to_string()),
            ("code", code.to_string()),
            ("client_id", client_id),
            ("client_secret", client_secret),
            ("redirect_uri", self.redirect_uri.clone()),
        ];
        if let Some(verifier) = consumed.pkce_verifier {
            form.push(("code_verifier", verifier));
        }
        let resp = HTTP
            .post(self.token_url.as_deref().ok_or_else(no_tenant)?)
            .form(&form)
            .send()
            .await
            .context("Failed to reach the Microsoft 365 token endpoint")?;
        if !resp.status().is_success() {
            let status = resp.status();
            let body = talos_http_body::read_error_text_capped(resp).await;
            let preview = talos_text_util::truncate_at_char_boundary(&body, 500);
            tracing::error!(
                status = %status,
                body_len = body.len(),
                body_preview = %talos_dlp_provider::redact_str(preview),
                "Microsoft 365 token exchange failed"
            );
            return Err(anyhow!(
                "Microsoft 365 token exchange failed (HTTP {status})"
            ));
        }

        #[derive(serde::Deserialize)]
        struct TokenResponse {
            access_token: String,
            refresh_token: Option<String>,
            expires_in: Option<u64>,
            scope: Option<String>,
        }
        let tokens: TokenResponse = talos_http_body::read_json_capped(resp)
            .await
            .context("Failed to parse the Microsoft 365 token response")?;
        // Without a refresh token the connection would die within the hour
        // and look healthy until then. Whether one came back is the test, not
        // whether the granted scopes name `offline_access`: Microsoft does
        // not always list it.
        let refresh_token = tokens
            .refresh_token
            .filter(|t| !t.is_empty())
            .ok_or_else(|| anyhow!(ConnectRefusal::NoRefreshToken))?;
        let granted = tokens.scope.unwrap_or_default();
        // A tenant's admin can consent to fewer scopes than were asked for. A
        // connection that can read neither the mailbox nor the calendar is
        // refused here, where it can be said, rather than stored and
        // discovered as 403s on the first run.
        //
        // The tokens just issued are dropped, unstored. Microsoft has no
        // per-token revoke; the owner removes the app at
        // myapplications.microsoft.com.
        let reading = reading_scopes_granted(&granted);
        if reading.is_empty() {
            return Err(anyhow!(ConnectRefusal::NoMailOrCalendarScope));
        }
        let token_expires_at = talos_oauth::oauth_expires_at(tokens.expires_in);

        // ---- 2. Which account is this -----------------------------------
        let resp = HTTP
            .get(&self.account_url)
            .bearer_auth(&tokens.access_token)
            .send()
            .await
            .context("Microsoft 365 account lookup failed")?;
        if !resp.status().is_success() {
            return Err(anyhow!(
                "Microsoft 365 account lookup failed (HTTP {})",
                resp.status()
            ));
        }
        // `id` is Graph's stable id for the user (an object id for a work or
        // school account), so reconnecting updates the row instead of adding
        // one. A sign-in name can be renamed; it is the label only.
        #[derive(serde::Deserialize)]
        #[serde(rename_all = "camelCase")]
        struct Account {
            id: String,
            user_principal_name: Option<String>,
            mail: Option<String>,
        }
        let account: Account = talos_http_body::read_json_capped(resp)
            .await
            .context("Failed to parse the Microsoft 365 account response")?;
        let provider_key = provider_key_for(&account.id)?;
        let account_label = account
            .user_principal_name
            .filter(|s| !s.trim().is_empty())
            .or(account.mail.filter(|s| !s.trim().is_empty()));

        // ---- 3. The row, then the tokens -----------------------------------
        // A token with no row would be refreshed with no card to disconnect
        // it from. So the row is written first; if the tokens then cannot be
        // stored, the row is hidden again.
        let integration = self
            .upsert_integration(
                user_id,
                &provider_key,
                account_label.as_deref(),
                token_expires_at,
                &granted,
            )
            .await?;
        if let Err(e) = cred_svc
            .store_credentials(
                user_id,
                PROVIDER,
                &provider_key,
                &tokens.access_token,
                Some(refresh_token.as_str()),
                token_expires_at,
                &granted,
                vec![],
            )
            .await
        {
            if let Err(hide) = sqlx::query(
                "UPDATE microsoft_365_integrations SET is_active = FALSE WHERE id = $1 AND user_id = $2",
            )
            .bind(integration.id)
            .bind(user_id)
            .execute(&self.db_pool)
            .await
            {
                tracing::error!(
                    integration_id = %integration.id,
                    error = %hide,
                    "Microsoft 365 tokens could not be stored and the connection row could not be hidden again"
                );
            }
            return Err(e.context("Failed to store Microsoft 365 credentials"));
        }

        // The account label is not logged.
        tracing::info!(
            target: "talos_audit",
            event_kind = "microsoft_365_connected",
            user_id = %user_id,
            integration_id = %integration.id,
            scopes = %reading.join(" "),
            "Microsoft 365 connected"
        );
        Ok(integration)
    }
}

/// Why a callback that reached Microsoft and got tokens is still refused.
#[derive(Debug, PartialEq, Eq)]
pub enum ConnectRefusal {
    /// The token response carried no refresh token.
    NoRefreshToken,
    /// The consent granted neither `Mail.Read` nor `Calendars.Read`.
    NoMailOrCalendarScope,
}
impl std::fmt::Display for ConnectRefusal {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::NoRefreshToken => f.write_str("Microsoft returned no refresh token"),
            Self::NoMailOrCalendarScope => {
                f.write_str("the consent granted neither Mail.Read nor Calendars.Read")
            }
        }
    }
}
impl std::error::Error for ConnectRefusal {}

/// Which of [`READING_SCOPES`] are in `granted`. Microsoft returns the granted
/// scopes space-separated, sometimes as full resource URIs
/// (`https://graph.microsoft.com/Mail.Read`) and in either case; both forms
/// count.
fn reading_scopes_granted(granted: &str) -> Vec<&'static str> {
    let got: Vec<String> = granted
        .split([' ', ','])
        .filter(|s| !s.is_empty())
        .map(|s| {
            let s = s.to_ascii_lowercase();
            s.strip_prefix("https://graph.microsoft.com/")
                .map(str::to_string)
                .unwrap_or(s)
        })
        .collect();
    READING_SCOPES
        .iter()
        .copied()
        .filter(|want| got.iter().any(|g| g.eq_ignore_ascii_case(want)))
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use talos_oauth::OAuthIntegration;

    fn service(client: Option<(&str, &str)>) -> Microsoft365Service {
        let pool = sqlx::postgres::PgPoolOptions::new()
            .connect_lazy("postgres://unused@127.0.0.1:1/unused")
            .expect("lazy pool");
        let token_url = TOKEN_URL
            .as_deref()
            .expect("MICROSOFT_365_TENANT is unset in tests");
        Microsoft365Service::for_tests(pool, client, token_url, ACCOUNT_URL)
    }

    #[tokio::test]
    async fn the_consent_is_under_its_own_provider_and_comes_back_here() {
        let svc = service(Some(("client-id", "client-secret")));
        let req = svc.authorize_request().expect("configured");
        assert_eq!(
            (req.provider, svc.provider()),
            ("microsoft_365", "microsoft_365")
        );
        assert_eq!(
            req.redirect_uri,
            "http://localhost:8000/api/microsoft-365/callback"
        );
        assert_eq!(Some(req.auth_url), AUTH_URL.as_deref());
        assert_eq!(Some(req.token_url), TOKEN_URL.as_deref());
        assert_eq!(req.extra_params, &[("prompt", "select_account")]);
    }

    #[test]
    fn the_consent_asks_for_a_refresh_token_and_reads_only() {
        assert!(SCOPES.contains(&"offline_access"));
        for scope in SCOPES {
            assert!(
                !scope.contains("Write") && !scope.contains("Send") && !scope.ends_with(".All"),
                "{scope}"
            );
        }
        for scope in READING_SCOPES {
            assert!(SCOPES.contains(scope), "{scope}");
        }
    }

    #[test]
    fn the_endpoints_are_under_the_tenant() {
        // `MICROSOFT_365_TENANT` is unset here; `talos_oauth` tests the override.
        assert_eq!(
            AUTH_URL.as_deref().unwrap(),
            "https://login.microsoftonline.com/common/oauth2/v2.0/authorize"
        );
        assert_eq!(
            TOKEN_URL.as_deref().unwrap(),
            "https://login.microsoftonline.com/common/oauth2/v2.0/token"
        );
    }

    #[test]
    fn a_consent_that_can_read_nothing_is_told_apart() {
        assert_eq!(
            reading_scopes_granted("openid profile email User.Read Mail.Read Calendars.Read"),
            vec!["Mail.Read", "Calendars.Read"]
        );
        // Full resource URIs, and Microsoft's lower-casing, count too.
        assert_eq!(
            reading_scopes_granted(
                "https://graph.microsoft.com/mail.read https://graph.microsoft.com/User.Read"
            ),
            vec!["Mail.Read"]
        );
        assert!(reading_scopes_granted("User.Read offline_access").is_empty());
        assert!(reading_scopes_granted("").is_empty());
        // A longer scope that merely starts with one of ours is not it.
        assert!(reading_scopes_granted("Mail.ReadWrite Calendars.Read.Shared").is_empty());
    }

    #[test]
    fn an_account_object_id_keys_a_credential() {
        // Work or school: an object id. Personal: sixteen hex digits.
        for id in ["6e4b2f4a-1c3d-4e5f-8a9b-0c1d2e3f4a5b", "0123456789abcdef"] {
            assert_eq!(provider_key_for(id).unwrap(), id);
        }
    }

    #[tokio::test]
    async fn an_unconfigured_client_cannot_start_a_connect() {
        let svc = service(None);
        assert!(!svc.is_configured());
        assert!(svc.authorize_request().is_err());
        assert!(service(Some(("id", "secret"))).is_configured());
    }

    #[tokio::test]
    async fn the_client_secret_is_not_in_debug_output() {
        let shown = format!("{:?}", service(Some(("client-id", "s3cr3t-value"))));
        assert!(
            shown.contains("[REDACTED]") && !shown.contains("s3cr3t-value"),
            "{shown}"
        );
    }

    #[test]
    fn an_account_id_that_could_re_root_a_vault_path_is_refused() {
        assert_eq!(provider_key_for(" acct_123 ").unwrap(), "acct_123");
        assert_eq!(
            provider_key_for("user@example.com").unwrap(),
            "user@example.com"
        );
        for bad in ["", "   ", "a/b", "../x", "a b", &"x".repeat(129)] {
            assert!(provider_key_for(bad).is_err(), "{bad:?}");
        }
    }

    /// Fails until the provider's real endpoints replace the scaffold's.
    #[test]
    fn the_provider_endpoints_were_filled_in() {
        for url in [
            AUTH_URL.as_deref().unwrap(),
            TOKEN_URL.as_deref().unwrap(),
            ACCOUNT_URL,
        ] {
            assert!(
                url.starts_with("https://") && !url.contains("provider.example"),
                "{url} is still the scaffold's placeholder"
            );
        }
    }
}
